### ISSUE TITLE
error running python code

### ISSUE THREAD

**Issue by starlessboi** [allenta/zabbix-template-for-redis#3]
Hi
when I use your script to monitor redis,I get this error:
/usr/local/bin/zabbix-redis.py -i '6379, 6380, 6381, 7000, 7001, 7002, 7003, 7004, 7005' -t server send -c /etc/zabbix/zabbix_agentd.conf -s dev

Traceback (most recent call last):
  File "/usr/local/bin/zabbix-redis.py", line 380, in <module>
    main()
  File "/usr/local/bin/zabbix-redis.py", line 376, in main
    globals()[options.command](options)
  File "/usr/local/bin/zabbix-redis.py", line 101, in send
    items = stats(instance, options.redis_type)
  File "/usr/local/bin/zabbix-redis.py", line 240, in stats
    sys.stderr.write(output)
TypeError: write() argument must be str, not bytes

can you help me?
thanks

**Comment by starlessboi** [comment]
I think the problem is related to difference between how python 3 and 2 handles strings...because I'm using python 3, I got this error.
have you use this code under python 3?

**Comment by davidfb** [comment]
Hi @starlessboi,

No, this code has not been tested under Python 3. The problem seems indeed the differences between Python 2 and Python 3 string handling: `Popen.communicate` by default under Python 3 returns bytes instead of strings and thus its return values can't be written in `stderr` without a proper conversion.

A solution could be to set `universal_newlines` parameter to `True` in the `subprocess.Popen` call on line 298 but beware that other incompatibilities with Python 3 could be found in the code (for instance, usage of `iteritems` instead of `items`). We'll try to test all this in Python 3 as soon as possible.

**Comment by starlessboi** [comment]
Thanks for quick answer..look forward for your testings
